import { Client, dropsToXrp } from 'xrpl';
import type { ChainAdapter, WalletSnapshot, WalletTransaction } from '../types/wallet';
import { getPrices } from '../services/priceService';
import { isBitcoinAddress, isSolanaAddress, isXrpAddress } from './validators';

const timeout=async<T>(p:Promise<T>,ms=15000):Promise<T>=>Promise.race([p,new Promise<T>((_,rej)=>setTimeout(()=>rej(new Error('Request timed out')),ms))]);
const btcApi='https://blockstream.info/api';
const solRpc=import.meta.env.VITE_SOLANA_RPC_URL||'https://api.mainnet-beta.solana.com';
const fmt=(n:number,max=8)=>n.toLocaleString(undefined,{maximumFractionDigits:max});

const bitcoin:ChainAdapter={id:'bitcoin',name:'Bitcoin',symbol:'BTC',placeholder:'bc1q… or 1A1z…',validateAddress:isBitcoinAddress,explorerAddress:a=>`https://blockstream.info/address/${a}`,async lookupWallet(address){
 const [info,txs,tip]=await Promise.all([timeout(fetch(`${btcApi}/address/${encodeURIComponent(address)}`).then(r=>{if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json();})),timeout(fetch(`${btcApi}/address/${encodeURIComponent(address)}/txs`).then(r=>r.json())),timeout(fetch(`${btcApi}/blocks/tip/height`).then(r=>r.text()))]);
 const c=info.chain_stats,m=info.mempool_stats,sats=BigInt(c.funded_txo_sum||0)-BigInt(c.spent_txo_sum||0)+BigInt(m.funded_txo_sum||0)-BigInt(m.spent_txo_sum||0); const price=(await getPrices(['bitcoin'])).bitcoin;
 const transactions:WalletTransaction[]=txs.slice(0,20).map((tx:any)=>{let incoming=0n,outgoing=0n;for(const v of tx.vin||[])if(v.prevout?.scriptpubkey_address===address)outgoing+=BigInt(v.prevout.value||0);for(const v of tx.vout||[])if(v.scriptpubkey_address===address)incoming+=BigInt(v.value||0);const net=incoming-outgoing;const confirmed=Boolean(tx.status?.confirmed), conf=confirmed&&tx.status.block_height?Number(tip)-tx.status.block_height+1:0;return {hash:tx.txid,direction:net>0n?'incoming':net<0n?'outgoing':'activity',amount:fmt(Number(net<0n?-net:net)/1e8,8),timestamp:tx.status?.block_time,status:confirmed?'confirmed':'pending',confirmations:conf,counterparty:undefined,type:'Bitcoin transfer',fee:tx.fee?fmt(tx.fee/1e8,8):undefined,explorerUrl:`https://blockstream.info/tx/${tx.txid}`};});
 return {chain:'bitcoin',address,balance:{native:fmt(Number(sats)/1e8,8),symbol:'BTC',usd:price?Number(sats)/1e8*price:undefined},received:fmt(c.funded_txo_sum/1e8,8),sent:fmt(c.spent_txo_sum/1e8,8),transactionCount:c.tx_count,pendingCount:m.tx_count,transactions,explorerUrl:this.explorerAddress(address)};
}};

async function solCall(method:string,params:any[]){const endpoints=[solRpc,'https://api.mainnet-beta.solana.com'].filter((v,i,a)=>v&&!a.slice(0,i).includes(v));let last:unknown;for(const endpoint of endpoints){try{const r=await timeout(fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})}));if(!r.ok){last=Error(`RPC HTTP ${r.status}`);continue;}const j=await r.json();if(j.error)throw Error(j.error.message||'Solana RPC error');return j.result;}catch(err){last=err;}}throw last instanceof Error?last:Error('Unable to reach Solana RPC');}
const solana:ChainAdapter={id:'solana',name:'Solana',symbol:'SOL',placeholder:'Solana public key',validateAddress:isSolanaAddress,explorerAddress:a=>`https://solscan.io/account/${a}`,async lookupWallet(address){const [bal,sigs]=await Promise.all([solCall('getBalance',[address,{commitment:'confirmed'}]),solCall('getSignaturesForAddress',[address,{limit:20}])]);const price=(await getPrices(['solana'])).solana;const transactions:WalletTransaction[]=sigs.map((s:any)=>({hash:s.signature,direction:'activity',timestamp:s.blockTime||undefined,status:s.err?'failed':'confirmed',confirmations:undefined,type:'Solana transaction',explorerUrl:`https://solscan.io/tx/${s.signature}`}));const sol=bal.value/1e9;return {chain:'solana',address,balance:{native:fmt(sol,9),symbol:'SOL',usd:price?sol*price:undefined},transactionCount:sigs.length,transactions,explorerUrl:this.explorerAddress(address)};}};

const xrp:ChainAdapter={id:'xrp',name:'XRP Ledger',symbol:'XRP',placeholder:'rXXXXXXXXXXXXXXXXXXXXXXXX',validateAddress:isXrpAddress,explorerAddress:a=>`https://livenet.xrpl.org/accounts/${a}`,async lookupWallet(address){const client=new Client('wss://xrplcluster.com');try{await timeout(client.connect());const [info,history]=await Promise.all([client.request({command:'account_info',account:address,ledger_index:'validated'}),client.request({command:'account_tx',account:address,ledger_index_min:-1,ledger_index_max:-1,limit:20,forward:false})]);const price=(await getPrices(['xrp'])).xrp;const transactions:WalletTransaction[]=history.result.transactions.map((e:any)=>{const tx=e.tx||e;const meta=e.meta;const delivered=meta?.delivered_amount;const amount=typeof delivered==='string'?Number(dropsToXrp(delivered)):undefined;const dest=tx.Destination;const src=tx.Account;const direction=dest===address?'incoming':src===address?'outgoing':'activity';return {hash:tx.hash||e.hash,direction,amount:amount===undefined?undefined:fmt(amount,6),timestamp:tx.date?tx.date+946684800:undefined,status:meta?.TransactionResult==='tesSUCCESS'?'confirmed':'failed',type:tx.TransactionType||'XRPL activity',counterparty:direction==='incoming'?src:dest,explorerUrl:`https://livenet.xrpl.org/transactions/${tx.hash||e.hash}`};});const xrp=Number(dropsToXrp(info.result.account_data.Balance));return {chain:'xrp',address,balance:{native:fmt(xrp,6),symbol:'XRP',usd:price?xrp*price:undefined},transactionCount:transactions.length,transactions,explorerUrl:this.explorerAddress(address)};}finally{if(client.isConnected())await client.disconnect();}}};
export const adapters:Record<string,ChainAdapter>={bitcoin,solana,xrp};
