import { useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, Check, Copy, ExternalLink, Search, Activity } from 'lucide-react';
import { adapters } from './chains/adapters';
import { isBitcoinAddress, isSolanaAddress, isXrpAddress, short } from './chains/validators';
import type { ChainId, WalletSnapshot } from './types/wallet';

const chainIds:ChainId[]=['bitcoin','solana','xrp'];
const samples={bitcoin:'bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh',solana:'11111111111111111111111111111111',xrp:'rG1QQv2nh2gr7RCZ1P8YYcBUKCCN633jCn'};
function App(){const [chain,setChain]=useState<ChainId>('bitcoin');const [address,setAddress]=useState('');const [snapshot,setSnapshot]=useState<WalletSnapshot|null>(null);const [status,setStatus]=useState<'idle'|'loading'|'error'>('idle');const [error,setError]=useState('');const adapter=adapters[chain];
 async function search(e?:React.FormEvent){e?.preventDefault();const value=address.trim();if(!adapter.validateAddress(value)){setError(`That doesn't look like a valid ${adapter.name} address.`);setStatus('error');return;}setStatus('loading');setSnapshot(null);try{setSnapshot(await adapter.lookupWallet(value));setStatus('idle');}catch(err){setError(err instanceof Error?err.message:'Unable to fetch wallet data.');setStatus('error');}}
 function select(c:ChainId){setChain(c);setSnapshot(null);setStatus('idle');setError('');}
 return <div className="shell"><header><div className="brand"><div className="brand-mark">◈</div><div><div className="eyebrow">CRYPTGREG RESEARCH</div><h1>Chain Intelligence</h1></div></div><span className="live"><i/> READ-ONLY DATA</span></header><main><section className="hero"><p className="kicker">MULTI-CHAIN WALLET EXPLORER</p><h2>See the signal<br/><em>on-chain.</em></h2><p className="intro">A focused view of wallet balances and activity across Bitcoin, Solana, and XRP Ledger.</p></section><div className="card"><div className="tabs">{chainIds.map(id=><button key={id} className={chain===id?'active '+id:''} onClick={()=>select(id)}>{adapters[id].name}</button>)}</div><form onSubmit={search} className="search"><input value={address} onChange={e=>setAddress(e.target.value)} placeholder={adapter.placeholder} aria-label={`${adapter.name} address`} spellCheck={false}/><button disabled={status==='loading'}>{status==='loading'?<span className="spinner"/>:<Search size={18}/>}<span>{status==='loading'?'Fetching':'Inspect wallet'}</span></button></form><div className="hint">Public address only · no keys or wallet connection required · <button type="button" onClick={()=>{setAddress(samples[chain]);setTimeout(()=>search(),0)}}>try a sample</button></div>{status==='error'&&<div className="notice error">{error}</div>}{status==='loading'&&<div className="state"><span className="spinner large"/>Reading validated network data…</div>}{snapshot&&<Dashboard snapshot={snapshot}/>} {!snapshot&&status==='idle'&&<div className="state empty"><Activity size={30}/><strong>Choose a chain and inspect a wallet</strong><span>Results stay in your browser and are never stored.</span></div>}</div></main><footer>Data from public network APIs · For research &amp; education only · <a href="https://github.com/jimskin03/multi-chain-tracker">View source</a></footer></div>}
function Dashboard({snapshot}:{snapshot:WalletSnapshot}){const [copied,setCopied]=useState(false);const copy=()=>{navigator.clipboard?.writeText(snapshot.address);setCopied(true);setTimeout(()=>setCopied(false),1200)};return <section className="dashboard"><div className="wallet-head"><div><span className="label">{snapshot.chain} balance</span><div className="balance">{snapshot.balance.native} <small>{snapshot.balance.symbol}</small></div>{snapshot.balance.usd!==undefined&&<div className="usd">≈ ${snapshot.balance.usd.toLocaleString(undefined,{maximumFractionDigits:2})} USD</div>}</div><div className="address"><span>{short(snapshot.address)}</span><button onClick={copy} aria-label="Copy address">{copied?<Check size={15}/>:<Copy size={15}/>}</button><a href={snapshot.explorerUrl} target="_blank" rel="noreferrer"><ExternalLink size={15}/></a></div></div><div className="metrics"><Metric label="Transactions" value={snapshot.transactionCount?.toLocaleString()||'—'}/><Metric label="Received" value={snapshot.received||'—'}/><Metric label="Sent" value={snapshot.sent||'—'}/><Metric label="Pending" value={snapshot.pendingCount?.toString()||'0'}/></div><div className="tx-title"><h3>Latest activity</h3><span>{snapshot.transactions.length} shown</span></div>{snapshot.transactions.length===0?<div className="no-tx">No transaction history returned.</div>:<div className="transactions">{snapshot.transactions.map(tx=><a className="tx" key={tx.hash} href={tx.explorerUrl} target="_blank" rel="noreferrer"><span className={'direction '+tx.direction}>{tx.direction==='incoming'?<ArrowDownLeft size={17}/>:tx.direction==='outgoing'?<ArrowUpRight size={17}/>:<Activity size={16}/>}</span><span className="tx-main"><strong>{tx.amount?`${tx.direction==='incoming'?'+':tx.direction==='outgoing'?'−':''}${tx.amount} ${snapshot.balance.symbol}`:tx.type}</strong><small>{short(tx.hash)} · {tx.status}</small></span><ExternalLink size={14}/></a>)}</div>}</section>}
function Metric({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
export default App;
